[package]
name = "crossroads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet_datalink = "0.31.0"
pnet_packet = "0.31.0"
